### ISSUE TITLE
response with headers isn't matched

### ISSUE THREAD

**Issue by bradwood** [CircleUp/aresponses#21]
Hi all,

Are there any thoughts of implementing this? Or any ideas how to do it?

I'm doing this

```python
@pytest.mark.asyncio
async def test_listing_fetch_206(aresponses):

    async def get_handler_206(request):
        xmlfile_path = Path(__file__).resolve().parent.joinpath('fetch_payload.xml')
        LOGGER.debug(f'xml file path = {xmlfile_path}')
        LOGGER.debug(f'request headers = {request.headers}')

        rng = request.http_range
        with open(xmlfile_path, 'rb') as f:
            f.seek(rng.start)
            data = f.read(rng.stop - rng.start)
            hdr = {'Content-Range': f'bytes {rng.start}-{rng.stop - 1}/{xmlfile_path.stat().st_size}'}
            #LOGGER.debug(f'resp header = {hdr}')
            resp = aresponses.Response(status=206, reason='OK', text=str(data), headers=hdr)
        return resp

    aresponses.add('foo.com', '/feed/6715', 'get', response=get_handler_206)

    # aresponses.add(aresponses.ANY, aresponses.ANY, aresponses.ANY, response=get_handler_206)


    #with isolated_filesystem():
    l = Listing('http://foo.com/feed/6715')
    await l.fetch(range_size=100)
    assert l._path.joinpath(l._filename).is_file()

```
I need to set the `Content-Range` header to have the mock serve Partial Content but when I set that on my Response object the match fails...

```
[2018-10-08 20:02:01,001] DEBUG:asyncio:Using selector: KqueueSelector
[2018-10-08 20:02:01,003] DEBUG:pyskyq.listing:Listing initialised: <List: url='http://foo.com/feed/6715', path='.epg_data', filename='ea51e77b9fdede19528d599f50182d37edcdbc082b06358146041fe446f6a855.xml'>
[2018-10-08 20:02:01,004] DEBUG:pyskyq.listing:Fetch(<List: url='http://foo.com/feed/6715', path='.epg_data', filename='ea51e77b9fdede19528d599f50182d37edcdbc082b06358146041fe446f6a855.xml'>) called started.
[2018-10-08 20:02:01,004] DEBUG:pyskyq.listing:Client session created. About to fetch url=http://foo.com/feed/6715
[2018-10-08 20:02:01,008] INFO:aresponses.main:Looking for match for foo.com /feed/6715 GET
[2018-10-08 20:02:01,009] DEBUG:tests.test_listing:xml file path = /Users/brad/Code/pyskyq/tests/fetch_payload.xml
[2018-10-08 20:02:01,009] DEBUG:tests.test_listing:request headers = <CIMultiDictProxy('Range': 'bytes=0-99', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'Host': 'foo.com', 'User-Agent': 'Python/3.7 aiohttp/3.4.4', 'AResponsesIsSSL': '')>
[2018-10-08 20:02:01,011] DEBUG:tests.test_listing:resp header = {'Content-Range': 'bytes 0-99/292'}
[2018-10-08 20:02:01,012] INFO:aiohttp.access:127.0.0.1 [08/Oct/2018:19:02:01 +0000] "GET /feed/6715 HTTP/1.1" 206 322 "-" "Python/3.7 aiohttp/3.4.4"
[2018-10-08 20:02:01,013] DEBUG:pyskyq.listing:Attempting byte range download. Range = 0-100
[2018-10-08 20:02:01,013] INFO:pyskyq.listing:Server responsed with status: 206.
[2018-10-08 20:02:01,015] DEBUG:pyskyq.listing:Headers: <CIMultiDictProxy('Content-Range': 'bytes 0-99/292', 'Content-Length': '139', 'Content-Type': 'text/plain; charset=utf-8', 'Date': 'Mon, 08 Oct 2018 19:02:01 GMT', 'Server': 'Python/3.7 aiohttp/3.4.4')>
[2018-10-08 20:02:01,042] INFO:aresponses.main:Looking for match for foo.com /feed/6715 GET
[2018-10-08 20:02:01,042] ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/Users/brad/.virtualenvs/pyskyq-4vSEKDfZ/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 390, in start
    resp = await self._request_handler(request)
  File "/Users/brad/.virtualenvs/pyskyq-4vSEKDfZ/lib/python3.7/site-packages/aresponses/main.py", line 61, in _handler
    return await self._find_response(request)
  File "/Users/brad/.virtualenvs/pyskyq-4vSEKDfZ/lib/python3.7/site-packages/aresponses/main.py", line 106, in _find_response
    raise self._exception  # noqa
Exception: No Match found for foo.com /feed/6715 GET.  Host Match: False  Path Match: False
[2018-10-08 20:02:01,063] INFO:aiohttp.access:127.0.0.1 [08/Oct/2018:19:02:01 +0000] "GET /feed/6715 HTTP/1.1" 500 910 "-" "Python/3.7 aiohttp/3.4.4"
```

Any suggestions?

Thanks

Brad

**Comment by brycedrennan** [comment]
Brad, how many requests will be necessary to handle this?  You need something like this:
```python
for _ in range(1000):
    aresponses.add('foo.com', '/feed/6715', 'get', response=get_handler_206)
```

**Comment by bradwood** [comment]
Thanks @brycedrennan, that works.

I didn't realise each match was a 1-time use only thing, but, thinking about it now, it makes sense due to https://github.com/CircleUp/aresponses/blob/master/aresponses/main.py#L94.

Thanks again for you help!

Brad
