### ISSUE TITLE
Usage with pytest-aiohttp 

### ISSUE THREAD

**Issue by mvalkon** [CircleUp/aresponses#33]
The documentation states that with `pytest-aiohttp` one should re-initialise the mock server like below

```python
from aresponses import ResponsesMockServer

@pytest.fixture
async def aresponses(loop):
    async with ResponsesMockServer(loop=loop) as server:
        yield server
```

However following this documentation and passing the `aresponses`-fixture to my test function, I get the following error

```
tests/test_foo.py::test_foo[pyloop]
  /Users/mvalkonen/Library/Caches/pypoetry/virtualenvs/test-py3.7/lib/python3.7/site-packages/aresponses/main.py:53: DeprecationWarning: The object should be created from async function
    srv = Server(self._handler, loop=self._loop, debug=True, **kwargs)
```

I can reproduce this with the following example

```python
@pytest.fixture
async def aresponses(loop):
    async with ResponsesMockServer(loop=loop) as server:
        yield server


async def test_foo(aresponses):
    pass
```

How should one use `aresponses` with `pytest-aiohttp`?

**Comment by brycedrennan** [comment]
Is that an error or only a warning?

**Comment by brycedrennan** [comment]
Looks like aiohttp changed something on their end: https://github.com/aio-libs/aiohttp/issues/3331

We'll have to look at what the recommended pattern is going forward.

**Comment by mvalkon** [comment]
It is only a warning, but I still cannot use `aresponses`. I thought I'll try with an empty project without `pytest-aiohttp`, and see if it works with the most bare bones imitation of what I'd like to do. Maybe what I am trying is simply not possible?

```python
import pytest

import aiohttp

class Foo:
     async def test(self, url):
         async with aiohttp.ClientSession() as session:
             response = await session.post(url, json={"some_field": "some_value"})
             return await response.json()


@pytest.mark.asyncio
async def test_foo(aresponses):
    url = "http://localhost.com/foo"
    response = aresponses.Response(body=b'{"status":"ok"}', status=200)
    aresponses.add("http://localhost.com", "/foo", "POST", response)
    result = await Foo().test(url)
    print(result)
```

Running this with pytest gives me two exceptions

```python 
ERROR    aiohttp.server:web_protocol.py:355 Error handling request
Traceback (most recent call last):
  File "/Users/mvalkonen/Library/Caches/pypoetry/virtualenvs/test-py3.7/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/Users/mvalkonen/Library/Caches/pypoetry/virtualenvs/test-py3.7/lib/python3.7/site-packages/aresponses/main.py", line 60, in _handler
    return await self._find_response(request)
  File "/Users/mvalkonen/Library/Caches/pypoetry/virtualenvs/test-py3.7/lib/python3.7/site-packages/aresponses/main.py", line 108, in _find_response
    raise self._exception  # noqa
Exception: No Match found for localhost.com /foo POST.  Host Match: False  Path Match: False
```

and then finally

```python
RuntimeError: Event loop stopped before Future completed.
```

I'm sure I'm doing something wrong, but the documentation is a little scant so someone new to asyncio and aiohttp might be struggling.

**Comment by brycedrennan** [comment]
Hostname shouldn't have `http://` in it.  Should be like this:
```python
aresponses.add("localhost.com", "/foo", "POST", response)
```
